name: Publish to NPM (including canaries and prereleases)

on:
  push:
    branches-ignore:
      # No canary deploys for branches opened by dependabot
      - 'dependabot/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    name: Make a release and publish to NPM

    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 16.3.0

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: |
          yarn build

      # https://github.com/lerna/lerna/issues/3026#issuecomment-1079901176
      - name: Add auth credentials for npm
        run: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        run: npm run release-auto
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
